### PR TITLE
Add missing empty types

### PR DESCRIPTION
**Pull request by Shatur**
I also noticed that some variations of empty types is missing. In this PR I added all variations for empty types.

### CODE REVIEW

**Comment by fire** [comment]
In the middle of something so I can't check the blender. What do you mean by empty types?

**Comment by Shatur** [comment]
I meant Blender's empty objects. I added the following empty object types to the scene (an empty `Cube` object was already present):
изображение

To check "and the others not listed" I also added a `Circle` object.

**Comment by fire** [comment]
Typo on the commit message.

**Comment by Shatur** [comment]
Thanks. Amended.

**Pull request merged**
