### PR TITLE
Add missing -convcol hint

### PR DESCRIPTION
**Pull request by Shatur**
I noticed that `-convcol` is missing in `32678-respect-import-hints-with-empty.blend`.

### CODE REVIEW

**Comment by fire** [comment]
Can you also update the associated files?

`blender --background --python blend_export.py`

**Comment by Shatur** [comment]
I tried it before this PR and have a different `.fbx` files. Maybe because of a different Blender version? I use 2.90.1.
Is it okay if I update them with my version of Blender?

**Comment by fire** [comment]
Use your version. It’s fine. Probably want to log your version in the description.

**Comment by Shatur** [comment]
Done.

Should I create a separate file for the hints from https://github.com/godotengine/godot/pull/39105? (in another PR, of course).

**Comment by fire** [comment]
Up to you. There are advantages of seeing the files in the same file and advantages of having a new file.

**Pull request merged**
