### PR TITLE
Comment cleanup for the cubic interpolate with.

### PR DESCRIPTION
**Pull request by fire**
Update Crosshair.gd, DebugLines.gd, and 6 more files...

### CODE REVIEW

**Comment by fire** [comment]
@GNSS-Stylist Any comments?

**Comment by GNSS-Stylist** [comment]
Looks good to me as this seem to contain removed obsolete comments etc. ~~Tried to open this in somewhat recent (few days old) compile from master and there were some issues like some renamings (deg2rad has changed to deg_to_rad, File to FileAccess etc). Probably also last line of LOScriptReplayer need to changed "back" to non-transposed version (Godot 3.x-way). I have fixed these in my other project and can manually merge to this (in separate pull-request?) if you like?~~

Are these tests targeted for godot 4 (master-branch)?

**Comment by fire** [comment]
I am targeting godot 4 master yes.

**Comment by GNSS-Stylist** [comment]
Sorry about my comment above. I tried this in a hurry (on monday morning) and didn't notice I was working on another branch and the issues were already fixed... And you seemed to already fix also the camera control toggle in https://github.com/godotengine/godot-tests/pull/27 I also noticed. So everything that's left is "looks good to me".

**Pull request merged**
