### PR TITLE
Adds tests for 45545

### PR DESCRIPTION
**Pull request by abaire**
Adds automated tests for godotengine/godot#45545

### CODE REVIEW

**Comment by abaire** [comment]
Hey @fire I started writing some tests for the change to/removal of `_sanitize_scene_name`. Does this look like a reasonable start? Once I have a change that passes the basics I plan on adding tests to ensure bones are still properly attached as well.

**Comment by fire** [comment]
I'll try to look near the weekend, don't wait for me.

**Comment by abaire** [comment]
Still a little bit of work to be done, but I think this is ready for a first pass.

Remaining bits:
1. The emoji tests fail because the current JSON tokenizer can't parse them yet (@bruvzg proposed a fix in the review for godotengine/godot/pull/45545 that fixes this).
2. The animation checking code doesn't work correctly yet, the resolution of clashing animation names produces results where the animation name doesn't match the node name since it's dependent on the ordering in the glTF file. I think we can probably just ignore the naming and simply check to make sure the animation properly references the correct node instead.
3. Still need to add a skeleton test, but I expect it'll behave similarly to the animation case since I'm not planning on changing bone sanitization in 45545 (happy to do a followup though).

**Comment by abaire** [comment]
Animation checking code is fixed, added a skeleton test. Emoji tests still fail without the patch from @bruvzg (as expected), but generate nodes that are referenceable if you know that the emoji chars will be replaced by the replacement chars (I'd propose leaving as is if the improvement to the JSON tokenizer is likely to be accepted).

**Comment by fire** [comment]
Is this ready to be merged?

**Comment by abaire** [comment]
I think so. It looks like I can't add reviewers on this repo though (and there doesn't seem to be an automatically assigned reviewer like on the main repo).

**Review by Calinou — APPROVED** [review]

**Comment by fire** [comment]
Thanks for contributing to Godot Engine.

**Pull request merged**
