### PR TITLE
Add test files for material import hints

### PR DESCRIPTION
**Pull request by Shatur**
I noticed that there are no files for testing material hints. Needed to test the fix from https://github.com/godotengine/godot/pull/48167.

### CODE REVIEW

**Comment by fire** [comment]
There is a typo on the material filename for the blend.

However, other than that it's to be merged when the other pr is merged.

**Comment by Shatur** [comment]
> There is a typo on the material filename for the blend.

Thanks, fixed.

> However, other than that it's to be merged when the other pr is merged.

Awesome. Could you make a review for https://github.com/godotengine/godot/pull/48167?

**Comment by fire** [comment]
There is still a typo. Try again. Thanks for the work.

**Comment by Shatur** [comment]
> There is still a typo. Try again. Thanks for the work.

You are right, just forgot to remove old generated files, thanks.

**Comment by fire** [comment]
I'm not sure about the status of this. 

The corresponding pr was limbo'ed.

**Pull request closed without merging**
