### PR TITLE
Add additional import hints

### PR DESCRIPTION
**Pull request by Shatur**
I added objects with new hints introduced in https://github.com/godotengine/godot/pull/39105:

изображение

### CODE REVIEW

**Comment by Shatur** [comment]
Interesting thing: Blender generates `.fbx` files with different checksums on every export.

**Comment by fire** [comment]
This pr will have to wait until the Godot Engine pr is merged.

**Comment by Shatur** [comment]
@fire, could your review the mentioned PR?

**Comment by fire** [comment]
What do you think about splitting feature proposal tests versus official tests?

**Comment by Shatur** [comment]
> What do you think about splitting feature proposal tests versus official tests?

Do you mean to put it in a separate folder?

**Comment by fire** [comment]
Yeah.

I'm thinking we can merge as is and then move then from proposal to the regular location.

Something like #######-proposal-title or proposal/blend/#######-proposal-title.blend

**Comment by Shatur** [comment]
I would just not merge this PR until the corresponding PR in Godot is accepted.
But if it is more convenient for you, then I will update the location.

**Comment by Shatur** [comment]
Done! I also updated the script.

**Comment by fire** [comment]
Thanks.

**Comment by Shatur** [comment]
I noticed that there is no Collada exports. Are you planning to add it? I can send PR if so.

**Comment by fire** [comment]
Go ahead, I had trouble.

**Pull request merged**
